[package]
edition = "2018"
name = "rss_downloader"
version = "0.1.0"

[dependencies]
feed = "2.1.0"
reqwest = {version = "0.11.9", features = ["blocking"]}
rss = {version = "2.0.0", features = ["url"]}
urlencoding = "2.1.0"
